default: &default
  adapter: postgresql
  encoding: unicode
  username: web_task_list
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  host: localhost
  database: web_task_list_development
  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice
test:
  <<: *default
  host: localhost
  database: web_task_list_test
production:
  <<: *default
  database: web_task_list_production
  url: <%= ENV['DATABASE_URL'] %>
